language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - git clone https://github.com/schrodinger/pymol-open-source.git
  - cd pymol-open-source
  - python setup.py build install
install:
  - pip install pytest
# command to run tests
script: pytest
