language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install build-essential python-dev python-pmw libglew-dev 
  - sudo apt-get install freeglut3-dev libpng-dev libfreetype6-dev libxml2-dev 
  - sudo apt-get install libmsgpack-dev libglm-dev
  - git clone https://github.com/schrodinger/pymol-open-source.git
  - cd pymol-open-source
  - python setup.py build install
install:
  - pip install pytest
# command to run tests
# script: pytest # TODO: enable after addind tests
