name: simumoleEnv
channels:
  - omnia
  - conda-forge
  - schrodinger
  - defaults
dependencies:
  - pdbfixer=1.5=py37_0
  - pymol=2.3.2=py37h75f9260_0
  - pip:
    - django==2.2.2
    - django-formtools==2.1
    - py3wetransfer==0.0.2
    - python-magic==0.4.15
    - pytz==2019.1
    - sqlparse==0.3.0
