# Generated by Django 2.2 on 2019-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('file_name', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
